"""create initial tables

Revision ID: 4787cc109936
Revises: 
Create Date: 2026-07-08 16:10:04.274004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4787cc109936'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status_user', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=30), server_default='USER', nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('USER', 'SUPER_ADMIN')", name='check_users_role'),
    sa.CheckConstraint("status_user IN ('Pending', 'Active', 'Inactive', 'Locked')", name='check_users_status_user'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('label_title', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('notification_preferences',
    sa.Column('preference_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email_frequency', sa.String(length=30), server_default='INSTANT', nullable=False),
    sa.Column('email_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('app_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("email_frequency IN ('INSTANT', 'DAILY_DIGEST', 'WEEKLY_DIGEST', 'OFF')", name='check_notification_preferences_email_frequency'),
    sa.CheckConstraint("scope IN ('USER_ACCOUNT', 'SUPER_ADMIN')", name='check_notification_preferences_scope'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('preference_id')
    )
    op.create_table('spaces',
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('name_space', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status_space', sa.String(length=20), server_default='Active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status_space IN ('Active', 'Archived', 'Deleted')", name='check_spaces_status_space'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('space_id')
    )
    op.create_table('user_tokens',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('access_expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('verification_token',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("token_type IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET')", name='check_verification_token_token_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('space_members',
    sa.Column('space_member_id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='Active', nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('OWNER', 'MEMBER')", name='check_space_members_role'),
    sa.CheckConstraint("status IN ('Active', 'Removed')", name='check_space_members_status'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.space_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('space_member_id'),
    sa.UniqueConstraint('space_member_id')
    )
    op.create_table('sprints',
    sa.Column('sprint_id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), server_default='2', nullable=True),
    sa.Column('status', sa.String(length=20), server_default='Active', nullable=False),
    sa.Column('auto_start', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('auto_complete', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('Planned', 'Active', 'Completed', 'Deleted')", name='check_sprints_status'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.space_id'], ),
    sa.PrimaryKeyConstraint('sprint_id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('sprint_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('task_status', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('story_points', sa.Float(), server_default='0', nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("priority IN ('HIGH', 'MEDIUM', 'LOW')", name='check_tasks_priority'),
    sa.CheckConstraint("task_status IN ('new', 'in_progress', 'in_testing', 'pending_review', 'done', 'need_revision', 'cancelled')", name='check_tasks_task_status'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.space_id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.sprint_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('space_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=30), server_default='USER', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("audience IN ('USER', 'OWNER', 'SUPER_ADMIN')", name='check_notifications_audience'),
    sa.CheckConstraint("type IN ('task_assigned', 'task_mentioned', 'task_created', 'task_updated', 'task_deleted', 'status_changed', 'priority_changed', 'comment_added', 'comment_edited', 'comment_deleted', 'attachment_added', 'due_today', 'due_date_changed', 'task_overdue', 'user_registered', 'account_locked', 'user_verified', 'user_deactivated', 'role_changed', 'permission_changed', 'space_created', 'space_updated', 'space_member_added', 'space_role_changed', 'owner_space_update', 'audit_log_event', 'system_alert')", name='check_notifications_type'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.space_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('task_assignees',
    sa.Column('assignee_entry_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=False),
    sa.Column('assignee_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('assignee_entry_id'),
    sa.UniqueConstraint('assignee_entry_id')
    )
    op.create_table('task_assignment_history',
    sa.Column('assignment_history_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('previous_assignee_id', sa.UUID(), nullable=True),
    sa.Column('new_assignee_id', sa.UUID(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('change_status', sa.String(length=20), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("change_status IN ('new', 'in_progress', 'in_testing', 'pending_review', 'done', 'need_revision', 'cancelled')", name='check_task_assignment_history_change_status'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['new_assignee_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['previous_assignee_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('assignment_history_id')
    )
    op.create_table('task_attachments',
    sa.Column('attachment_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('task_comments',
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['task_comments.comment_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_comments')
    op.drop_table('task_attachments')
    op.drop_table('task_assignment_history')
    op.drop_table('task_assignees')
    op.drop_table('notifications')
    op.drop_table('tasks')
    op.drop_table('sprints')
    op.drop_table('space_members')
    op.drop_table('verification_token')
    op.drop_table('user_tokens')
    op.drop_table('spaces')
    op.drop_table('notification_preferences')
    op.drop_table('audit_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
