"""increase id columns to varchar 15

Revision ID: 5006fd421313
Revises: 9b3fdfc22149
Create Date: 2026-07-08 16:44:48.822146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5006fd421313'
down_revision: Union[str, Sequence[str], None] = '9b3fdfc22149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'log_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("('AUD'::text || lpad((nextval('audit_logs_log_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('notification_preferences', 'preference_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("('NPF'::text || lpad((nextval('notification_preferences_preference_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('notification_preferences', 'user_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('notifications', 'notification_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("('NTF'::text || lpad((nextval('notifications_notification_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('notifications', 'actor_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('notifications', 'task_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('notifications', 'space_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('space_members', 'space_member_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("('SPM'::text || lpad((nextval('space_members_space_member_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('space_members', 'space_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('space_members', 'user_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('spaces', 'space_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("('SPC'::text || lpad((nextval('spaces_space_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('spaces', 'owner_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('sprints', 'sprint_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("('SPR'::text || lpad((nextval('sprints_sprint_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('sprints', 'space_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('task_assignees', 'assignee_entry_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("('TAS'::text || lpad((nextval('task_assignees_assignee_entry_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('task_assignees', 'task_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('task_assignees', 'assignee_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('task_assignment_history', 'assignment_history_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("('TAH'::text || lpad((nextval('task_assignment_history_assignment_history_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('task_assignment_history', 'task_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('task_assignment_history', 'previous_assignee_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('task_assignment_history', 'new_assignee_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('task_assignment_history', 'changed_by',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('task_attachments', 'attachment_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("('TAT'::text || lpad((nextval('task_attachments_attachment_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('task_attachments', 'task_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('task_attachments', 'uploaded_by',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('task_comments', 'comment_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("('TCM'::text || lpad((nextval('task_comments_comment_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('task_comments', 'task_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('task_comments', 'user_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('task_comments', 'parent_comment_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('tasks', 'task_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("('TSK'::text || lpad((nextval('tasks_task_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('tasks', 'space_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('tasks', 'sprint_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('tasks', 'creator_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('user_tokens', 'token_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("('UTK'::text || lpad((nextval('user_tokens_token_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('user_tokens', 'user_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('users', 'user_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("('USR'::text || lpad((nextval('users_user_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('verification_token', 'token_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("('VTK'::text || lpad((nextval('verification_token_token_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('verification_token', 'user_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_token', 'user_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('verification_token', 'token_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("('VTK'::text || lpad((nextval('verification_token_token_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('users', 'user_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("('USR'::text || lpad((nextval('users_user_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('user_tokens', 'user_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('user_tokens', 'token_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("('UTK'::text || lpad((nextval('user_tokens_token_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('tasks', 'creator_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('tasks', 'sprint_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.alter_column('tasks', 'space_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('tasks', 'task_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("('TSK'::text || lpad((nextval('tasks_task_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('task_comments', 'parent_comment_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.alter_column('task_comments', 'user_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('task_comments', 'task_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('task_comments', 'comment_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("('TCM'::text || lpad((nextval('task_comments_comment_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('task_attachments', 'uploaded_by',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('task_attachments', 'task_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('task_attachments', 'attachment_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("('TAT'::text || lpad((nextval('task_attachments_attachment_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('task_assignment_history', 'changed_by',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('task_assignment_history', 'new_assignee_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.alter_column('task_assignment_history', 'previous_assignee_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.alter_column('task_assignment_history', 'task_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('task_assignment_history', 'assignment_history_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("('TAH'::text || lpad((nextval('task_assignment_history_assignment_history_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('task_assignees', 'assignee_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('task_assignees', 'task_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('task_assignees', 'assignee_entry_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("('TAS'::text || lpad((nextval('task_assignees_assignee_entry_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('sprints', 'space_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('sprints', 'sprint_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("('SPR'::text || lpad((nextval('sprints_sprint_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('spaces', 'owner_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('spaces', 'space_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("('SPC'::text || lpad((nextval('spaces_space_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('space_members', 'user_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('space_members', 'space_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('space_members', 'space_member_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("('SPM'::text || lpad((nextval('space_members_space_member_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('notifications', 'space_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.alter_column('notifications', 'task_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.alter_column('notifications', 'actor_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('notifications', 'notification_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("('NTF'::text || lpad((nextval('notifications_notification_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('notification_preferences', 'user_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'preference_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("('NPF'::text || lpad((nextval('notification_preferences_preference_id_seq'::regclass))::text, 8, '0'::text))"))
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('audit_logs', 'log_id',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("('AUD'::text || lpad((nextval('audit_logs_log_id_seq'::regclass))::text, 8, '0'::text))"))
    # ### end Alembic commands ###
